# Generated by Django 5.0.2 on 2025-05-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_forecastmodel_demandforecast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastmodel',
            name='product',
        ),
        migrations.DeleteModel(
            name='DemandForecast',
        ),
        migrations.DeleteModel(
            name='ForecastModel',
        ),
    ]
