# Generated by Django 5.0.2 on 2025-05-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_customerportalorder_customerportalorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerportalorder',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerportalorder',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
