# Generated by Django 5.0.2 on 2025-05-13 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_customerportalorder_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerportalorder',
            name='internal_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_order', to='main_app.order'),
        ),
    ]
