# Generated by Django 5.0.2 on 2025-05-13 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0008_remove_forecastmodel_product_delete_demandforecast_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file', models.FileField(upload_to='forecast_models/')),
                ('last_trained', models.DateTimeField(auto_now=True)),
                ('metrics', models.JSONField(default=dict, help_text='Model performance metrics')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_app_model', to='main_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('forecast_value', models.FloatField(help_text='Forecasted demand quantity')),
                ('lower_bound', models.FloatField(help_text='Lower bound of forecast (95% confidence interval)')),
                ('upper_bound', models.FloatField(help_text='Upper bound of forecast (95% confidence interval)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_app_forecasts', to='main_app.product')),
            ],
            options={
                'ordering': ['product', 'date'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
